language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: PmcKTup/AOV3JCFPI8wba45TbQOvfHnWlMmOydSThLKc0ZIiwz4I5lJ1u0VOvR6jFMOvDRzZk3UAdedgPUvOngK7onP2IjgDuCy5zODpmimfTn0UzZGsl9bEBsGqvqQBoRNjDj0trn29JeVjGocjgmanUf1NG0rl/Vb85ALYumaUhr2jhT+8gZYuQZMe7yyGnuSc8mmbvGBNwu86knGIrnne8v9x6v7DuxEIsQdK9ZTNNdtaVUPxxoBCRMfL/VP4sKZePFpKcIA9nuFyam3N72dFOTFJRyOOSbjQsK5gYkhYIEjwMiHNVShZm09FsCnJVWGFKFTvIVz6bV/hvCRQ0sAtXmyVWZ3Wx1INA6Fs9aMnn+Tmd8iGqCbcHl+jQuW28YBaooLtvL01/bUW2Ju+9RiOocavw5zmM0OuTMy8/dWuWADcMd36qT8JQEEntwD124f5vrPhAmJqDvWmxW53AQR4Ee1lo976HNigA+RQseYmfOZm5bzcDFfgpK/ofIriGBUaTdYqdlc347XpFuwjHAudTFSBIhDcuEX1ns8+ACl1TVyB3066fNa6MNmnI+hCEg7FKsUjYSLrfyp+s/zwMj3T9E9UmE6NzF3G7IG1L8tAu2882ikUBA6g3ZK13qHjd0lC+11B+RkraDlnP98/19/FodUGIp3GUOEusP7FPK4=
  app: node-lms
  on:
    repo: edwinmah/node-lms
    branch: master
